<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net8.0-android</TargetFrameworks>
        <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Lab1.Models\Lab1.Models.csproj" />
    </ItemGroup>
</Project>